### ISSUE TITLE
unable to see the adv_drop_count in the podlevel metrics

### ISSUE THREAD

**Issue by abhipatwari17** [microsoft/retina#369]
I am using retina in my project . 
i have enabled the advance level pod metrics.
I am able to see the adv_forward_count metrics , drop_bytes, drop_count and so .
But i am unable to get the metrics of adv_drop_count . Please let me know if i have to add anything .
i have attached MetricsConfiguration file below. 

```
apiVersion: retina.sh/v1alpha1
kind: MetricsConfiguration
metadata:
  name: metricsconfigcrd
spec:
  contextOptions:
    - metricName: drop_count
      sourceLabels:
        - ip
        - podname
        - port
      additionalLabels:
        - direction
        - reason
      destinationLabels:
        - ip
        - podname
        - port
        - workload
    - metricName: forward_count
      sourceLabels:
        - ip
        - podname
        - port
      additionalLabels:
        - direction
      destinationLabels:
        - ip
        - podname
        - port
        - workload
  namespaces:
    include:
      - default
      - kube-system
 ```
 
 
 
![image](https://github.com/microsoft/retina/assets/88781436/4a2f9096-d460-4359-bcad-ae3333a766a0)

**Comment by huntergregory** [comment]
Thanks for raising this issue. On my setup, I also don't see any `adv_drop_` metrics. We will need to dig into the code to understand why.

I have retina v0.0.5 with the following ConfigMap:
```yaml
$ k get cm retina-config -oyaml
apiVersion: v1
data:
  config.yaml: |-
    apiServer:
      host: 0.0.0.0
      port: 10093
    logLevel: info
    enabledPlugin: [dropreason,packetforward,linuxutil,dns,packetparser]
    metricsInterval: 10
    enableTelemetry: false
    enablePodLevel: true
    remoteContext: false
    enableAnnotations: true
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: retina
    meta.helm.sh/release-namespace: kube-system
  creationTimestamp: "2024-04-15T06:53:58Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: retina-config
  namespace: kube-system
```
