### ISSUE TITLE
Duplicate command and args blocks in hubble helm templates

### ISSUE THREAD

**Issue by whatnick** [microsoft/retina#651]
**Describe the bug**
Hubble helm operator deployment templates have duplicate command and args keys , especially if using the `values.yaml` where these are defined and the template already contains these.

```yaml
        - command:
            - /retina-operator
          args:
            - --config-dir=/retina
          image: {{ .Values.operator.repository }}:{{ .Values.operator.tag }}
          imagePullPolicy: {{ .Values.operator.pullPolicy }}
          name: retina-operator
          {{- if .Values.operator.container.command }}
          command:
          {{- range .Values.operator.container.command }}
          - {{ . }}
          {{- end }}
          {{- end }}
          {{- if .Values.operator.container.args}}
          args:
          {{- range $.Values.operator.container.args}}
          - {{ . | quote }}
          {{- end}}
          {{- end}}
```

**To Reproduce**
Attempt to deploy the helm chart. The following error is encountered.

```
Helm upgrade failed for release kube-system/retina with chart retina@0.0.1: error while running post render on files: map[string]interface {}(nil): yaml: unmarshal errors: line 55: mapping key "command" already defined at line 48 line 57: mapping key "args" already defined at line 50 Last Helm logs: 2024-08-26T07:10:50.827534506Z: preparing upgrade for retina 2024-08-26T07:10:50.836051119Z: resetting values to the chart's original version
```

**Expected behavior**
Helm deploys cleanly

**Screenshots**

**Platform (please complete the following information):**

- OS: Amazon Linux
- Kubernetes Version: 1.28
- Host: EKS
- Retina Version: v0.0.14

**Additional context**
Happy to provide a small PR removing the duplicated sections and wrapping them in if-else
